Add mainpageView
code-squad/javascript-reservation pull request #1
Opened 2018-03-06 02:51 UTC by sphilee

메인페이지 슬라이딩기능까지 했습니답

2018-03-06 06:29 UTC, crongro requested changes
helper에 메서드가 많이 늘었네요.

좀더 범용적인 아이들인지, 고민해보세요.
아무거나 이리로 들어가지 못하게.

그리고 helper안의 비슷한 성질(network처리, animation처리등)이 보이면 이를 객체나 클래스로 묶어두는 건 어떨까요?

2018-03-06 06:29 UTC, nigayo commented on src/css/swipecustom.scss
> +  width: 100% !important;
important 는 원인이 파악되지 않은 상태에서 조치하는 것이라면 가급적 안쓰는 게 좋긴해요.

2018-03-06 06:29 UTC, nigayo commented on src/helpers.js
> +export function moveScroll(to) {
이함수는 특정동작을 담고 있어서, 재사용이 될까요? 
지금 위치가 helper.js 에 있으니 범용적으로 동작되게 수정해보면 좋겠어요. 

easeInQuad가 있다거나, Math.abs(change / 4); 이런코드라던가. 
이런 구체적인 동작은 변경될 확률도 클거 같아서요.

2018-03-06 06:29 UTC, nigayo commented on src/helpers.js
> +function easeInOutQuad(t, b, c, d) {
여기 구현된 코드를 말할 수 있도록, 수학적인 이해를 하면 더 좋겠군요. 
예를들어 easeInOutQuad를 기반으로 효과를 조금 변경시킨다면? 아래 코드를 어떻게 바꾸면 된다거나..
즉 수학적인원리를 이해해서 변경도 가능할정도로요.

2018-03-06 06:29 UTC, nigayo commented on src/controller.js
> +            .bind('transitionend')
bind와 chaining으로 일관된 동작을 구현하고 있는데, 괜찮아요.
그런데 단점은 없나요?  아마 다른 구조로 동작도 가능할 거 같아요.
this.mainSlideView.bind('transitionend', 'slideNavi', 'autoPlay') 이런식으로 동작도 할 수 있겠네요.

지금은 뭐가 좋은지 잘 모르겠지만, bind방식이 가진 장/단점을 좀더 고민해보면서 다른 방식으로 처리하는 것도 고민해보세요.

2018-03-06 06:29 UTC, nigayo commented on src/controller.js
> +    resetSlide({index, thresHoldL, thresHoldR}) {
중복코드를 없앨 수 있을까요? 
-1과 +1차이밖에 없어보이는데..

2018-03-06 06:29 UTC, nigayo commented on src/css/swipecustom.scss
> +    width: 19px;
SCSS를 쓰면서 자주 사용하는 값들은 변수개념을 좀 사용해보면 어때요?

2018-03-06 06:29 UTC, nigayo commented on src/view/mainpageView.js
> +        this
왜 갑자기 this 하고 한줄 넘기는거죠? ㅎ

2018-03-06 06:29 UTC, nigayo commented on src/view/mainpageView.js
> +    clone() {
이름이 너무 범용적인데요. 조금더 구체적으로해보죠.

2018-03-06 07:36 UTC, sphilee commented on src/view/mainpageView.js
> +        this
라인단위로 디버깅하기 쉽게 위해 하였습니답

2018-03-08 11:00 UTC, sphilee commented
@nigayo 예약하기까지 끝냈습니답

2018-03-12 07:08 UTC, sphilee commented
@nigayo 
- 모바일 터치 이벤트
- fetch API 사용
- 폴더 구조 변경
- webpack 플러그인 사용
- webpack dev, production 분리

2018-03-12 10:16 UTC, crongro approved these changes
웹팩기능이 추가되고 있군요.

테스트코드도 좀 완성해보죠~

2018-03-12 10:16 UTC, nigayo commented on src/reserve-controller.js
> +        const emailRegEx = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
이거 정확히 이해한거임? ㅎㅎ 
잘모르는 코드면 아는 코드로 다시 구현하세요. 
(알거라 믿음)

2018-03-15 03:16 UTC, crongro reviewed
puppeteer 활용 좋네요.
좀더 다양한 테스팅해보세요.

2018-03-15 03:16 UTC, nigayo commented on src/mainpage/test/test.js
> +    expect(html).toBe('예약확인');
이거 뭐 테스트 한거에요?

2018-03-15 03:16 UTC, nigayo commented on src/mainpage/test/test.js
> +import puppeteer from 'puppeteer';
오~ 찾아보니 puppeteer 을 이용한 unit test 예제가 많이 있네요.참고해서 해보면 좋겠습니다.

2018-03-15 08:47 UTC, crongro requested changes
잘 했어요~ 
좀더  UI테스트 케이스 더 만들어보죠.

2018-03-16 02:55 UTC, crongro approved these changes
테스트 코드는 테스트 가능한 것부터 하는 것도 필요하고, 
동시에 중요한 인터랙션의 테스트도 고려해야합니다.
그래서 좀 어렵긴하지만. 아무튼 그 두 개의 교집합을 정해서 하는게 좋긴해요.

2018-03-16 02:55 UTC, nigayo commented on src/mainpage/test/test.js
> +        test('cache item Test', async() => {
설명을 좀 길게 넣긴해요. cache item Test 라기보다는, 
시나리오를 문장으로 쓰는 것이죠. 어려운면 한글도 가능.

2018-03-16 02:55 UTC, nigayo commented on src/mainpage/test/test.js
> +            expect(await page.$$('.active .item ')).toHaveLength(3);
8,3 이런 숫자가 어떤 의도인지 잘 나타나지 않으니 변수로 담가두죠.
const ALL_ITEM_COUNT = 8; 이런식으로.

2018-03-16 02:55 UTC, nigayo commented on src/mainpage/test/test.js
> +            expect(await page.$$('.active .item ')).toHaveLength(8);
8개인지 확인하는 것도 좋고요. 
추가로는 랜덤한 번호의 아이템(7이나8번째등)에 어떤 실제 콘텐츠가 있는지(그 내용이 뭔지는 모르나)를 확인하는 것도 좋겠네요.
예를들어 그 텍스트의 문자열길이가 0이상이면 데이터가 화면에 표현됐구나~ 라고 예상할 수 있게요.

2018-03-20 01:02 UTC, crongro reviewed
wow 테스트 커버리지!
얼마나 나오는 지 궁금하네요.

2018-03-20 04:32 UTC, sphilee commented
![image](https://user-images.githubusercontent.com/20538040/37636094-2a9d8c98-2c43-11e8-85d1-1f309f92e75d.png)

2018-03-21 01:58 UTC, nigayo commented
커버리지 괜찮은데요? ㅎㅎ 
커버리지 더 올려보면 좋겠는데 어때요? 

그리고,
beforeEach 에서 DOM추가하는 게 꽤 길다보니..좀 보긴 안좋은데요. html문자열을 다른 파일로 분리시키는 것도 고려해볼 수준.. 물론 작으면 test코드에서 같이 보이는 게 더 좋을 거 같고요.

2020-02-19 06:11 UTC, closed without merging